
pipeline
{
    agent any
    stages
    {
        stage("Día Lunes")
        {
            steps
            {
                println "Lunes"
            }
        }
        stage("Día Martes")
        {
            steps
            {
                script
                {
                def fechaActual = new Date()
                println fechaActual    
                }
                
            }
        }
        stage("Dia Miercoles")
        {
            
            steps
            {
                println "Miercoles"
            }
            
        }
        
        stage("Día Jueves")
        {
            steps
            {
                println("Jueves")
            }
            
        }
        stage("Dia Viernes")
        {
            steps
            {
                script
                {
                    def cause = currentBuild.rawBuild.getCause(Cause.UserIdCause)
                    if (cause != null) {
                    def user = cause.userId ?: 'anonymous'
                    echo "started by ${user}"
                    } else 
                    {
                    echo "started some other way"
                    }
                println cause
                }
            }
        }        
    }
}
